# Generated by Django 6.0.2 on 2026-03-12 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
