# Generated by Django 6.0.2 on 2026-03-12 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_api', '0002_alter_report_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
