# Generated by Django 6.0.2 on 2026-03-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports_api", "0003_alter_report_report_date"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                fields=("user", "report_type", "report_date"),
                name="unique_user_report_type_per_day",
            ),
        ),
    ]
